---
- name: Check for AWS CLI
  ansible.builtin.command: which aws
  register: aws_cli_check
  changed_when: false
  failed_when: false

- name: Download AWS CLI v2 installer
  ansible.builtin.get_url:
    url: "{{ aws_cli_zip_url }}"
    dest: "{{ aws_cli_zip_path }}"
    mode: "0644"
  when: aws_cli_check.rc != 0

- name: Extract AWS CLI v2 installer
  ansible.builtin.unarchive:
    src: "{{ aws_cli_zip_path }}"
    dest: /tmp
    remote_src: true
  when: aws_cli_check.rc != 0

- name: Install AWS CLI v2
  ansible.builtin.command: "{{ aws_cli_extract_dir }}/install"
  args:
    creates: /usr/local/bin/aws
  when: aws_cli_check.rc != 0

- name: Verify AWS CLI
  ansible.builtin.command: aws --version
  changed_when: false
